spring.application.name=medicine-reminder-bot
spring.profiles.active=local

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/medicine_reminder}
spring.datasource.username=${DATABASE_USERNAME:}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false